id: P000621
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG24995
  title: གཟན་ཆག་གི་ལས་སྣོན་བསྲེས་སྦྱོར་དང་ཉིན་རེའི་གཟན་ཆག་སྦྱོར་སྡེབ།
  author: ''
  volumes:
    6a501c174e804fe19b7f14e84b4d7af8:
      image_group_id: I1KG24997
      title: ''
      volume_number: 1
      total_pages: 68
